export default {
  UPDATE_LAYOUT_SECTIONS: 'UPDATE_LAYOUT_SECTIONS',
  UPDATE_ACTIVE_SECTION: 'UPDATE_ACTIVE_SECTION',
  UPDATE_ACTIVE_PROP: 'UPDATE_ACTIVE_PROP',
  UPDATE_FORM_MODEL: 'UPDATE_FORM_MODEL',
  UPDATE_FORM_OPTIONS: 'UPDATE_FORM_OPTIONS',
  UPDATE_ITERATION_IDX: 'UPDATE_ITERATION_IDX',
  UPDATE_FORM_SETTING: 'UPDATE_FORM_SETTING',
  UPDATE_FORM_LAYOUT: 'UPDATE_FORM_LAYOUT',
  UPDATE_FORM_CONTROL: 'UPDATE_FORM_CONTROL',
  RESET_GLOBAL_STORE: 'RESET_GLOBAL_STORE'
}
